#!/bin/bash
set -e
# apply-power-settings.sh — regenerate hypridle.conf based on dock state and power-settings.conf
#
# Reads DOCKED_/UNDOCKED_ settings, checks current dock state, generates the
# appropriate hypridle.conf, and restarts hypridle.
#
# Called by:
#   - dock-monitor.sh on dock/undock transitions
#   - power-settings-gui.py after saving settings
#   - Hyprland startup (via dock-monitor.sh)

CONFIG_FILE="$HOME/.config/power-settings.conf"
STATE_FILE="$HOME/.cache/dock-monitor.state"
HYPRIDLE_CONF="$HOME/.config/hypr/hypridle.conf"

# =============================================================================
# LOAD CONFIG
# =============================================================================

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "No power-settings.conf found, using defaults"
    exit 1
fi

source "$CONFIG_FILE"

# Detect old flat format (no DOCKED_ prefix) and migrate
if [[ -z "$DOCKED_SCREENSAVER_ENABLED" && -n "$SCREENSAVER_ENABLED" ]]; then
    cat > "$CONFIG_FILE" << 'MIGRATE'
# Power settings — dock-aware configuration
# Applied by apply-power-settings.sh on dock/undock transitions

# When undocked (laptop only)
UNDOCKED_SCREENSAVER_ENABLED="false"
UNDOCKED_SCREENSAVER_TIMEOUT="300"
UNDOCKED_AUTO_LOGOFF_ENABLED="false"
UNDOCKED_AUTO_LOGOFF_TIMEOUT="600"
UNDOCKED_LID_CLOSE_ACTION="poweroff"

# When docked (external monitor connected)
DOCKED_SCREENSAVER_ENABLED="true"
DOCKED_SCREENSAVER_TIMEOUT="300"
DOCKED_AUTO_LOGOFF_ENABLED="false"
DOCKED_AUTO_LOGOFF_TIMEOUT="600"
DOCKED_LID_CLOSE_ACTION="ignore"
MIGRATE
    source "$CONFIG_FILE"
fi

# =============================================================================
# DETERMINE DOCK STATE
# =============================================================================

dock_state=$(cat "$STATE_FILE" 2>/dev/null || echo "undocked")

if [[ "$dock_state" == "docked" ]]; then
    PREFIX="DOCKED"
else
    PREFIX="UNDOCKED"
fi

# Read settings for current dock state via indirect variable expansion
ss_enabled_var="${PREFIX}_SCREENSAVER_ENABLED"
ss_timeout_var="${PREFIX}_SCREENSAVER_TIMEOUT"
lo_enabled_var="${PREFIX}_AUTO_LOGOFF_ENABLED"
lo_timeout_var="${PREFIX}_AUTO_LOGOFF_TIMEOUT"

SCREENSAVER_ENABLED="${!ss_enabled_var:-false}"
SCREENSAVER_TIMEOUT="${!ss_timeout_var:-300}"
AUTO_LOGOFF_ENABLED="${!lo_enabled_var:-false}"
AUTO_LOGOFF_TIMEOUT="${!lo_timeout_var:-600}"

# =============================================================================
# GENERATE HYPRIDLE.CONF
# =============================================================================

# Remove symlink if install.sh created one — we manage this file directly
[[ -L "$HYPRIDLE_CONF" ]] && rm "$HYPRIDLE_CONF"

{
    echo "# AUTO-GENERATED by apply-power-settings.sh — do not edit manually"
    echo "# Dock state: $dock_state | Screensaver: $SCREENSAVER_ENABLED | Auto-logoff: $AUTO_LOGOFF_ENABLED"
    echo ""
    echo "general {"
    echo "    lock_cmd = hyprlock"
    echo "    before_sleep_cmd = loginctl lock-session"
    echo "    after_sleep_cmd = hyprctl dispatch dpms on"
    echo "}"

    if [[ "$SCREENSAVER_ENABLED" == "true" ]]; then
        echo ""
        echo "# Screen off (DPMS) after ${SCREENSAVER_TIMEOUT}s"
        echo "listener {"
        echo "    timeout = $SCREENSAVER_TIMEOUT"
        echo "    on-timeout = hyprctl dispatch dpms off"
        echo "    on-resume = hyprctl dispatch dpms on"
        echo "}"
    fi

    if [[ "$AUTO_LOGOFF_ENABLED" == "true" ]]; then
        echo ""
        echo "# Auto log off after ${AUTO_LOGOFF_TIMEOUT}s"
        echo "listener {"
        echo "    timeout = $AUTO_LOGOFF_TIMEOUT"
        echo "    on-timeout = hyprctl dispatch exit"
        echo "}"
    fi
} > "$HYPRIDLE_CONF"

# =============================================================================
# RESTART HYPRIDLE
# =============================================================================

killall hypridle 2>/dev/null || true
sleep 0.3
hypridle &
disown
