-- Generated by nwg-displays on 2026-03-15 at 13:46:33.
hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "628x1440",
    scale = 1,
})

hl.monitor({
    output = "DP-6",
    mode = "5120x1440@119.98",
    position = "1916x0",
    scale = 1,
})
